### ISSUE TITLE
QED evolution LO

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/eko#23] opened 2019-12-04 15:29 UTC
What Marek and Alan asked for more than one year ago :P

**Comment by felixhekhorn** [comment] 2020-06-03 10:01
talk by Paolo N in the seminar https://indico.cern.ch/event/918896/

**Comment by felixhekhorn** [comment] 2020-07-29 08:27
until we do, I use this place to collect references: https://arxiv.org/pdf/2007.14300.pdf seems like it is an active filed of research

**Comment by felixhekhorn** [comment] 2020-08-19 12:43
https://arxiv.org/pdf/2008.02895.pdf "Factorized approach to radiative corrections for inelastic lepton-hadron collisions"

**Comment by felixhekhorn** [comment] 2020-09-28 08:39
https://arxiv.org/pdf/2009.12220.pdf "Parton distributions in radiative corrections to the crosssection ofelectron-proton scattering"

**Comment by felixhekhorn** [comment] 2021-04-01 16:54
Hi,

During our last meeting we briefly discussed QED evolution equations, and I believe what we'll need are the DGLAP equations

- in the complex-mass scheme [1], with
- alpha set according to the Gmu scheme [2], i.e.

  alpha = sqrt(2)/pi * Gmu * | MW^2 * (1 - MW^2 / MZ^2) |

where

  MW^2 = mw^2 - i * gw * mw
  MZ^2 = mz^2 - i * gz * mz

are complex parameters using the real pole masses mw/mz, and widths gw/gz.

That's at least what we use in our theory calculations.

Do you already have a timeline for this feature?

Best,
Christopher

[1] https://arxiv.org/abs/1912.06823, sec. 6.6
[2] https://arxiv.org/abs/1912.06823, sec. 5

**Comment by AleCandido** [comment] 2021-04-12 08:12
Updated references on DGLAP QED solution:
- section 2.2.3 in [@scarrazza thesis](https://arxiv.org/pdf/1509.00209.pdf)
- section 2 of [photon PDF from LHC data](https://arxiv.org/pdf/1701.08553.pdf)
- appendix A in [APFEL's lepton PDF](https://arxiv.org/pdf/1508.07002.pdf)

**Comment by felixhekhorn** [comment] 2021-04-16 11:38
A comparison between LuxQED and DGLAP: https://indico.bnl.gov/event/9726/contributions/46331/
https://www.youtube.com/watch?v=wvvVMiHFfnI&list=PLSU3NGiXqGfkDc4pQOmfqQj1qc3LlqMKX&index=4 starting ~ 01:05:00

**Comment by juanrojochacon** [comment] 2021-04-27 06:57
https://inspirehep.net/literature/1840369 Calculation of photon-induced Drell-Yan by means of the structure function approach

**Comment by felixhekhorn** [comment] 2021-04-27 08:46
> https://arxiv.org/abs/1911.12040 might be a good starting place or eventually a possible comparison ...

https://github.com/gstagnit/ePDF

**Comment by felixhekhorn** [comment] 2021-06-15 16:33
This issue should really be split into two different ones:
- implement QED corrections to DGLAP -> is required for an APFEL replacement and seems methodologically in reach
- evolution of lepton PDFs (also described here https://arxiv.org/pdf/2103.09844.pdf ) -> is more complex and will due to the distributional character require some rework ...

**Comment by felixhekhorn** [comment] 2021-06-22 08:31
> A comparison between LuxQED and DGLAP: https://indico.bnl.gov/event/9726/contributions/46331/

the corresponding paper: https://arxiv.org/pdf/2106.10299.pdf

**Comment by felixhekhorn** [comment] 2021-08-31 08:55
https://arxiv.org/pdf/2108.13371.pdf - I guess it's mostly about yadism but also, of course, partly about eko

**Comment by felixhekhorn** [comment] 2021-11-11 10:00
MSHT20qed: https://arxiv.org/pdf/2111.05357.pdf

**Comment by felixhekhorn** [comment] 2022-03-25 16:31
With respect to reproducing 3.1 LUXQED: this is something that we never quite managed to do exactly (I think we got within 1%, after we spoke with you and Alessandro). The settings that we were using were:
```
      call SetPDFSet("NNPDF31_nnlo_as_0118_luxqed")
      call SetPerturbativeOrder(2)
      call SetMassScheme("FONLL-C")
      call EnableDampingFONLL(0)
      call EnableIntrinsicCharm(1)
      call SetPDFEvolution("truncated")
      call SetRenQRatio(1d0)
      call SetFacQRatio(1d0)
      call SetVFNS()
      call SetMaxFlavourAlpha(5)
      call SetMaxFlavourPDFs(5)
      call SetAlphaQCDRef(0.118d0, 91.2d0)
      call EnableNLOQEDCorrections(1)
      call SetAlphaQEDRef(0.007778d0, 91.2d0)
      call SetSmallxResummation(0, "LL")
*
*     Heavy quark treatment
*
      call SetPoleMasses(1.51d0, 4.92d0, 172.5d0)
      call SetTheory("QUniD")
*
      call SetZMass(91.1876d0)
      call SetWMass(80.398d0)
      call SetGFermi(0.000012d0)
      call SetSin2ThetaW(0.23126d0)
      call EnableTargetMassCorrections(1)
      call SetProtonMass(0.938d0)
      call LHAPDFgrid(100, 1.65d0, “SM_baseline")
```
Given that we couldn’t remake LUXQED perfectly, we decided to do something that was as internally consistent as possible within our project: we started with the 3.1 LUXQED baseline at the initial scale, then used a fixed collection of settings to generate a new LHAPDF grid which we called our ’SM baseline’. Everything other PDF in the paper is then produced with the same settings, but with dark parameters set to non-zero values, so that they are directly comparable to our ’SM baseline’. This is not necessarily very clear in the paper though, perhaps we should mention this point in v2.

---
Thanks @J-M-Moore for your above reply

**Comment by AleCandido** [comment] 2023-01-27 16:52
@felixhekhorn can we close this issue, or do you want to keep?

In case, you want to keep, I would definitely change name. However, the information here is better stored in the wiki or something else.

**Closed** 2023-01-30 16:46 UTC
Labels: physics
